- name: ensure libvirt is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - libvirt
    - libvirt-python

- name: modprobe kvm_intel
  modprobe:
    name: kvm_intel
    state: present

- name: start libvirtd
  service:
    name: libvirtd
    state: running
