- name: install instack-undercloud
  yum:
    name: instack-undercloud
    state: installed
  when: instack_host_install_instack_undercloud_rpm

- name: fact instack_vm_defined
  shell: virsh list --all | grep instack
  failed_when: false
  changed_when: false
  register: instack_vm_defined

- name: stop_before_instack_virt_setup
  shell: echo "Stopping on user's request."; false
  when: stop_before_instack_virt_setup

- name: run instack-virt-setup
  shell: |
    set -exo pipefail
    {
      export LIBVIRT_VOL_POOL={{ instack_host_libvirt_storage_pool }}
      {{ instack_virt_setup_cmd }}
    } 2>&1 | tee /tmp/instack-virt-setup.out
  args:
    chdir: "{{ stack_user_home }}"
  sudo: yes
  sudo_user: stack
  when: instack_vm_defined.rc != 0

- name: stop_after_instack_virt_setup
  shell: echo "Stopping on user's request."; false
  when: stop_after_instack_virt_setup
