- name: stopping point before_instack_prepare_for_overcloud
  shell: echo "Stopping on user's request."; false
  when: stopping_point == 'before_instack_prepare_for_overcloud'

- name: register prepare_for_overcloud_done
  shell: |
    source ./stackrc
    nova flavor-list | grep baremetal
  args:
    chdir: "{{ stack_user_home }}"
  sudo: yes
  sudo_user: stack
  changed_when: false
  failed_when: false
  register: prepare_for_overcloud_done

- name: prepare for overcloud
  shell: |
    set -exo pipefail
    {
      {{ instack_prepare_for_overcloud_cmd }}
    } 2>&1 | tee /tmp/instack-prepare-for-overcloud.out
  args:
    chdir: "{{ stack_user_home }}"
  sudo: yes
  sudo_user: stack
  when: prepare_for_overcloud_done.rc != 0
