- name: fetch undercloud VM IP address
  include: undercloud_ip.yml

- name: ensure socat is installed
  yum:
    name: socat
    state: present

- name: undercloud ssh forwarding
  include: ssh_forward.yml

- name: undercloud http forwarding
  include: http_forward.yml

- name: wait for undercloud ssh to become available
  wait_for:
    host: localhost
    port: "{{ instack_host_uc_ssh_port }}"
    search_regex: OpenSSH
    timeout: 300

- name: authorize keys in undercloud for ansible connection
  include: root_authorized_keys.yml

- name: add undercloud to ansible host inventory
  add_host:
    name: uc-{{ inventory_hostname }}
    groups: instack_undercloud
    ansible_ssh_host: "{{ inventory_hostname }}"
    ansible_ssh_port: "{{ instack_host_uc_ssh_port }}"
    ansible_ssh_user: root

- name: stopping point after_undercloud_forwarding
  shell: echo "Stopping on user's request."; false
  when: stopping_point == 'after_undercloud_forwarding'
