- name: install instack-undercloud package
  yum:
    name: instack-undercloud
    state: present
  when: instack_uc_install_instack_undercloud_rpm

- name: fact undercloud_deployed
  shell: systemctl status openstack-keystone | grep running
  changed_when: false
  failed_when: false
  register: undercloud_deployed

- name: stopping point before_instack_install_undercloud
  shell: echo "Stopping on user's request."; false
  when: stopping_point == 'before_instack_install_undercloud'

- name: install undercloud
  shell: |
    set -exo pipefail
    {
      {{ instack_install_undercloud_cmd }}
    } 2>&1 | tee /tmp/instack-install-undercloud.out
  args:
    chdir: "{{ stack_user_home }}"
  sudo: yes
  sudo_user: stack
  when: undercloud_deployed.rc != 0

- name: copy rc files from root to stack user
  shell: |
    cp /root/{{ item }} {{ stack_user_home }}/{{ item }}
    chown stack:stack {{ stack_user_home }}/{{ item }}
  with_items:
    - stackrc
    - tripleo-undercloud-passwords
