- hosts: instack_host
  roles:
    - stopping_point_validation
    - stack_user
    - yum_repos
    - tools
    - instack_libvirt_storage
    - instack_virt_setup
    - instack_uc_ip_and_forward
  vars:
    - instack_host_type: host

- hosts: instack_undercloud
  roles:
    - stack_user
    - yum_repos
    - tools
    - instack_undercloud
    - instack_overcloud_images
    - instack_prepare_for_overcloud
  vars:
    - instack_host_type: uc
