- name: make sure rsync is installed
  yum:
    name: rsync
    state: present

- name: upload overcloud images
  synchronize:
    src: "{{ overcloud_images_prebuilt_dir }}/"
    dest: "{{ stack_user_home }}"
