---
- name: fact instack_storage_pool_exists
  shell: virsh pool-dumpxml {{ instack_host_libvirt_storage_pool }}
  register: instack_storage_pool_exists
  changed_when: false
  failed_when: false

- name: Create storage pool path
  file:
    path: "{{ instack_host_libvirt_storage_path }}"
    state: directory

- name: Create instack pool
  shell: virsh pool-define-as {{ instack_host_libvirt_storage_pool }} dir --target {{ instack_host_libvirt_storage_path }}
  when: instack_storage_pool_exists.rc != 0

- name: Start instack pool
  shell: virsh pool-start instack
  when: instack_storage_pool_exists.rc != 0

- name: Set instack pool to autostart
  shell: virsh pool-autostart instack
  when: instack_storage_pool_exists.rc != 0
